language: python

# Enable container-based builds
sudo: false

# Enable PIP deps cache between builds
cache:
  directories:
    - $HOME/.cache/pip

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

# command to install dependencies
install:
  - "pip install ."
  - "pip install nose"
  - "pip install pyshould"

# command to run tests
script: nosetests

